name: cinephoria

services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: cinephoria_app
    volumes:
      - ../..:/app:cached
      - node_modules:/app/node_modules
      - symfony_cache:/app/var/cache
      - symfony_logs:/app/var/log
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongodb
      - mailhog
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      SERVER_NAME: :8000
      FRANKENPHP_CONFIG: "num_threads 4"
      DATABASE_URL: mysql://root:root@db:3306/cinephoria?serverVersion=11.4.0-MariaDB
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mariadb:11.4
    container_name: symfony_db_cinephoria
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinephoria
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  mongodb:
    image: mongo:7.0
    container_name: mongo_cinephoria
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_cinephoria
    ports:
      - "1025:1025"
      - "8025:8025"
    logging:
      driver: none

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_cinephoria
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_cinephoria
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8082:8081"
    depends_on:
      - mongodb

volumes:
  db_data:
  mongodb_data:
  node_modules:
  symfony_cache:
  symfony_logs: